import { useState } from 'react'

import useEngineStore from '../store/engineStore'
import { processImage } from '../engine/imageProcessor'

function generateVanillaScript(particles, canvasW, canvasH, config) {
  const data = JSON.stringify(particles.map(p => ({
    ox: +(p.originX * canvasW).toFixed(2),
    oy: +(p.originY * canvasH).toFixed(2),
    c: p.char,
    r: p.r, g: p.g, b: p.b,
    br: +p.brightness.toFixed(1),
  })))

  return `<!-- ASCII Particle Engine — generated by ascii-particle-engine -->
<canvas id="ascii-canvas" style="width:100%;height:100%;display:block;background:#0a0a0f"></canvas>
<script>
(function(){
  var canvas = document.getElementById('ascii-canvas');
  var ctx = canvas.getContext('2d');
  var dpr = window.devicePixelRatio||1;
  var W = canvas.offsetWidth, H = canvas.offsetHeight;
  canvas.width = W*dpr; canvas.height = H*dpr;
  ctx.scale(dpr,dpr);

  var CONFIG = {
    sensitivity: ${config.sensitivity},
    elasticity: ${config.elasticity},
    friction: ${config.friction},
    palette: '${config.colorPalette}'
  };

  var raw = ${data};
  var n = raw.length;
  var px=new Float32Array(n),py=new Float32Array(n);
  var vx=new Float32Array(n),vy=new Float32Array(n);
  var ox=new Float32Array(n),oy=new Float32Array(n);
  var chars=[],colors=[];

  function teal(br){var t=br/255;return 'rgb('+Math.round(20+t*80)+','+Math.round(80+t*175)+','+Math.round(70+t*148)+')';}
  function matrix(br){return 'rgb(0,'+Math.round(80+br/255*175)+',0)';}
  function sampled(r,g,b){return 'rgb('+r+','+g+','+b+')';}

  for(var i=0;i<n;i++){
    ox[i]=raw[i].ox; oy[i]=raw[i].oy;
    px[i]=Math.random()*W; py[i]=Math.random()*H;
    chars[i]=raw[i].c;
    if(CONFIG.palette==='matrix') colors[i]=matrix(raw[i].br);
    else if(CONFIG.palette==='sampled') colors[i]=sampled(raw[i].r,raw[i].g,raw[i].b);
    else colors[i]=teal(raw[i].br);
  }

  var mouse={x:-9999,y:-9999};
  canvas.addEventListener('mousemove',function(e){
    var r=canvas.getBoundingClientRect();
    mouse.x=e.clientX-r.left; mouse.y=e.clientY-r.top;
  });
  canvas.addEventListener('mouseleave',function(){mouse.x=-9999;mouse.y=-9999;});

  function loop(){
    ctx.clearRect(0,0,W,H);
    ctx.font='11px Courier New';ctx.textBaseline='middle';
    var r2=CONFIG.sensitivity*CONFIG.sensitivity;
    for(var i=0;i<n;i++){
      var dx=mouse.x-px[i],dy=mouse.y-py[i],d2=dx*dx+dy*dy;
      if(d2<r2&&d2>0.01){
        var d=Math.sqrt(d2),f=(CONFIG.sensitivity-d)/CONFIG.sensitivity;
        vx[i]-=dx/d*f*8; vy[i]-=dy/d*f*8;
      }
      vx[i]+=(ox[i]-px[i])*CONFIG.elasticity;
      vy[i]+=(oy[i]-py[i])*CONFIG.elasticity;
      vx[i]*=CONFIG.friction; vy[i]*=CONFIG.friction;
      px[i]+=vx[i]; py[i]+=vy[i];
      ctx.fillStyle=colors[i];
      ctx.fillText(chars[i],px[i],py[i]);
    }
    requestAnimationFrame(loop);
  }
  loop();
})();
</script>`
}

function generateReactComponent(particles, canvasW, canvasH, config) {
  const data = JSON.stringify(particles.map(p => ({
    ox: +(p.originX * canvasW).toFixed(2),
    oy: +(p.originY * canvasH).toFixed(2),
    c: p.char,
    r: p.r, g: p.g, b: p.b,
    br: +p.brightness.toFixed(1),
  })))

  return `import { useEffect, useRef } from 'react'

const PARTICLES = ${data}

const CONFIG = {
  sensitivity: ${config.sensitivity},
  elasticity: ${config.elasticity},
  friction: ${config.friction},
  palette: '${config.colorPalette}',
}

function color(p) {
  const t = p.br / 255
  if (CONFIG.palette === 'matrix') return \`rgb(0,\${Math.round(80 + t * 175)},0)\`
  if (CONFIG.palette === 'sampled') return \`rgb(\${p.r},\${p.g},\${p.b})\`
  return \`rgb(\${Math.round(20 + t * 80)},\${Math.round(80 + t * 175)},\${Math.round(70 + t * 148)})\`
}

export default function AsciiParticles({ style }) {
  const canvasRef = useRef(null)

  useEffect(() => {
    const canvas = canvasRef.current
    const ctx = canvas.getContext('2d')
    const dpr = window.devicePixelRatio || 1
    const W = canvas.offsetWidth, H = canvas.offsetHeight
    canvas.width = W * dpr; canvas.height = H * dpr
    ctx.scale(dpr, dpr)

    const n = PARTICLES.length
    const px = new Float32Array(n), py = new Float32Array(n)
    const vx = new Float32Array(n), vy = new Float32Array(n)
    const ox = new Float32Array(PARTICLES.map(p => p.ox))
    const oy = new Float32Array(PARTICLES.map(p => p.oy))
    const chars = PARTICLES.map(p => p.c)
    const colors = PARTICLES.map(color)

    for (let i = 0; i < n; i++) {
      px[i] = Math.random() * W; py[i] = Math.random() * H
    }

    const mouse = { x: -9999, y: -9999 }
    canvas.addEventListener('mousemove', e => {
      const r = canvas.getBoundingClientRect()
      mouse.x = e.clientX - r.left
      mouse.y = e.clientY - r.top
    })
    canvas.addEventListener('mouseleave', () => { mouse.x = -9999; mouse.y = -9999 })

    let raf
    function loop() {
      ctx.clearRect(0, 0, W, H)
      ctx.font = '11px Courier New'
      ctx.textBaseline = 'middle'
      const r2 = CONFIG.sensitivity ** 2
      for (let i = 0; i < n; i++) {
        const dx = mouse.x - px[i], dy = mouse.y - py[i], d2 = dx*dx+dy*dy
        if (d2 < r2 && d2 > 0.01) {
          const d = Math.sqrt(d2), f = (CONFIG.sensitivity - d) / CONFIG.sensitivity
          vx[i] -= dx/d*f*8; vy[i] -= dy/d*f*8
        }
        vx[i] += (ox[i] - px[i]) * CONFIG.elasticity
        vy[i] += (oy[i] - py[i]) * CONFIG.elasticity
        vx[i] *= CONFIG.friction; vy[i] *= CONFIG.friction
        px[i] += vx[i]; py[i] += vy[i]
        ctx.fillStyle = colors[i]
        ctx.fillText(chars[i], px[i], py[i])
      }
      raf = requestAnimationFrame(loop)
    }
    loop()
    return () => cancelAnimationFrame(raf)
  }, [])

  return <canvas ref={canvasRef} style={{ display: 'block', width: '100%', height: '100%', ...style }} />
}
`
}

const FORMATS = [
  { value: 'react',   label: 'React Component', desc: '.jsx — drop into any React project' },
  { value: 'vanilla', label: 'Vanilla HTML',     desc: '.html — works on any website' },
  { value: 'json',    label: 'Raw JSON Data',    desc: '.json — particle positions & config' },
]

export default function ExportPanel() {
  const [open, setOpen]       = useState(false)
  const [selected, setSelected] = useState('react')
  const { imageData, density, charSet, customChars, sensitivity, elasticity, friction, colorPalette } = useEngineStore()

  function download(content, filename, mime = 'text/plain') {
    const blob = new Blob([content], { type: mime })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href = url; a.download = filename; a.click()
    URL.revokeObjectURL(url)
  }

  function handleExport() {
    if (!imageData) return
    const { particles } = processImage(imageData, density, charSet, customChars)
    const cfg = { sensitivity, elasticity, friction, colorPalette }
    if (selected === 'react')   download(generateReactComponent(particles, 800, 600, cfg), 'AsciiParticles.jsx')
    else if (selected === 'vanilla') download(generateVanillaScript(particles, 800, 600, cfg), 'ascii-particles.html', 'text/html')
    else download(JSON.stringify({ particles, config: cfg }, null, 2), 'ascii-particles.json', 'application/json')
    setOpen(false)
  }

  return (
    <div style={{ padding: '12px 20px 14px', position: 'relative' }}>

      <button
        onClick={() => setOpen(!open)}
        disabled={!imageData}
        style={{
          width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          background: 'rgba(255,255,255,0.04)',
          border: '1px solid rgba(255,255,255,0.08)',
          borderRadius: 8, padding: '10px 14px',
          cursor: imageData ? 'pointer' : 'not-allowed',
          color: imageData ? '#ccc9c4' : '#3d3a35',
          fontSize: 13, fontFamily: 'inherit', fontWeight: 500,
          transition: 'all 0.15s',
        }}
        onMouseEnter={e => { if (imageData) e.currentTarget.style.background = 'rgba(255,255,255,0.07)' }}
        onMouseLeave={e => { if (imageData) e.currentTarget.style.background = 'rgba(255,255,255,0.04)' }}
      >
        <span>↓ Export</span>
        <span style={{ fontSize: 9, display: 'inline-block', transform: open ? 'rotate(180deg)' : 'none', transition: 'transform 0.2s' }}>▼</span>
      </button>

      {open && (
        <div style={{
          position: 'absolute', bottom: 'calc(100% - 2px)', left: 20, right: 20,
          background: '#1a1916', border: '1px solid rgba(255,255,255,0.09)',
          borderRadius: 10, overflow: 'hidden', marginBottom: 4,
          boxShadow: '0 -12px 32px rgba(0,0,0,0.7)',
        }}>
          {FORMATS.map((fmt) => {
            const on = selected === fmt.value
            return (
              <div
                key={fmt.value}
                onClick={() => setSelected(fmt.value)}
                style={{
                  padding: '11px 14px', cursor: 'pointer',
                  borderBottom: '1px solid rgba(255,255,255,0.05)',
                  background: on ? 'rgba(255,255,255,0.06)' : 'transparent',
                  display: 'flex', alignItems: 'center', gap: 10,
                  transition: 'background 0.1s',
                }}
                onMouseEnter={e => { if (!on) e.currentTarget.style.background = 'rgba(255,255,255,0.03)' }}
                onMouseLeave={e => { if (!on) e.currentTarget.style.background = 'transparent' }}
              >
                <div style={{
                  width: 14, height: 14, borderRadius: '50%', flexShrink: 0,
                  border: `2px solid ${on ? '#f0ede8' : '#3d3a35'}`,
                  background: on ? '#f0ede8' : 'transparent',
                  transition: 'all 0.15s',
                }} />
                <div>
                  <div style={{ color: on ? '#f0ede8' : '#7a7570', fontSize: 12, fontWeight: on ? 500 : 400 }}>
                    {fmt.label}
                  </div>
                  <div style={{ color: '#3d3a35', fontSize: 10, marginTop: 1 }}>{fmt.desc}</div>
                </div>
              </div>
            )
          })}
          <div style={{ padding: '10px 14px' }}>
            <button
              onClick={handleExport}
              style={{
                width: '100%',
                background: '#f0ede8', color: '#0d0c0b',
                border: 'none', borderRadius: 7,
                fontSize: 13, padding: '9px',
                cursor: 'pointer', fontFamily: 'inherit', fontWeight: 600,
                transition: 'opacity 0.15s',
              }}
              onMouseEnter={e => e.currentTarget.style.opacity = '0.85'}
              onMouseLeave={e => e.currentTarget.style.opacity = '1'}
            >
              Download
            </button>
          </div>
        </div>
      )}
    </div>
  )
}
